// ─────────────────────────────────────────────────────────────────────────────
// AllComponents — directory of every Tkx* component grouped by family.
//
// Click behaviour:
//   - If the component has a published docs page at /components/<slug>/
//     (Astro Starlight, autogenerated from docs-site/src/content/docs/
//     components/*.mdx), the chip is a real <a> to that URL. The reader
//     gets to the docs immediately — Props table, live demo, examples.
//   - Otherwise (component exists in the library but no MDX page yet),
//     the chip falls back to the RequestAccessDialog. That signals an
//     intent to the maintainer to prioritise writing docs for that one.
//
// The DOCUMENTED_SLUGS set below is the source of truth — keep it in
// sync with `ls docs-site/src/content/docs/components/*.mdx`. A future
// follow-up could replace this with a build-time Vite glob to remove
// the manual sync. Listed inline here so the click-handler branch is
// pure, no async, no import.meta.glob complexity in this commit.
// ─────────────────────────────────────────────────────────────────────────────

import { useState } from 'react';
import { RequestAccessDialog, type RequestTarget } from '../RequestAccessDialog';

// Slugs that have a real /components/<slug>/ page on the Astro docs site.
// Generated from `ls docs-site/src/content/docs/components/*.mdx` as of
// 2026-05-31 — 97 component pages (excluding the index.mdx page).
const DOCUMENTED_SLUGS = new Set<string>([
  'aadhaar-input', 'accordion', 'address-input', 'affix', 'alert', 'anchor',
  'app-bar', 'autocomplete', 'avatar', 'badge', 'bottom-nav', 'breadcrumb',
  'button', 'calendar-lunar', 'captcha', 'card', 'carousel', 'cascader',
  'chat', 'checkbox', 'checkout', 'clock', 'color-picker', 'command',
  'confetti', 'config-provider', 'currency-input', 'data-grid', 'date-picker',
  'divider', 'drawer', 'dropdown', 'empty', 'file-upload', 'font-provider',
  'form', 'icon', 'image', 'image-editor', 'input', 'kyc-inputs', 'layout',
  'list', 'live-feed', 'live-log', 'live-metrics', 'logo', 'markdown',
  'masonry', 'mentions', 'menu', 'modal', 'number-input', 'org-chart', 'otp',
  'pagination', 'payment-button', 'phone-input', 'playground', 'popover',
  'progress', 'qrcode', 'radio', 'rating', 'real-time-chart', 'result',
  'rich-text-display', 'segmented', 'select', 'seo', 'signature-pad',
  'skeleton', 'slider', 'snackbar', 'sortable', 'speed-dial', 'spin',
  'statistic', 'stepper', 'subscription', 'table', 'tabs', 'tag',
  'theme-builder', 'timeline', 'title', 'toast', 'toast-provider', 'toggle',
  'toolbar', 'tooltip', 'tour', 'transfer-list', 'tree-view', 'typography',
  'video-player', 'watermark',
]);

interface ComponentGroup {
  emoji: string;
  title: string;
  desc: string;
  components: { name: string; slug: string; isNew?: boolean }[];
}

const GROUPS: ComponentGroup[] = [
  {
    emoji: '🎨',
    title: 'Primitives',
    desc: 'Single-purpose UI building blocks',
    components: [
      { name: 'Alert', slug: 'alert' },
      { name: 'Avatar', slug: 'avatar' },
      { name: 'Badge', slug: 'badge' },
      { name: 'Breadcrumb', slug: 'breadcrumb' },
      { name: 'Button', slug: 'button' },
      { name: 'Card', slug: 'card' },
      { name: 'Divider', slug: 'divider' },
      { name: 'Empty', slug: 'empty' },
      { name: 'Icon', slug: 'icon' },
      { name: 'Image', slug: 'image' },
      { name: 'Logo', slug: 'logo' },
      { name: 'Pagination', slug: 'pagination' },
      { name: 'Progress', slug: 'progress' },
      { name: 'Result', slug: 'result' },
      { name: 'Skeleton', slug: 'skeleton' },
      { name: 'Spin', slug: 'spin' },
      { name: 'Tag', slug: 'tag' },
      { name: 'Tooltip', slug: 'tooltip' },
      { name: 'Typography', slug: 'typography' },
    ],
  },
  {
    emoji: '✨',
    title: 'Holographic (v3.1 → v3.12)',
    desc: '3D-tilt + iridescent foil. The full HUD-building toolkit.',
    components: [
      { name: 'HolographicSurface',  slug: 'holographic-surface' },
      { name: 'HolographicCard',     slug: 'holographic-card' },
      { name: 'HolographicAvatar',   slug: 'holographic-avatar' },
      { name: 'HolographicBadge',    slug: 'holographic-badge' },
      { name: 'HolographicButton',   slug: 'holographic-button' },
      { name: 'HolographicPanel',    slug: 'holographic-panel',    isNew: true },
      { name: 'HolographicGauge',    slug: 'holographic-gauge',    isNew: true },
      { name: 'HolographicProgress', slug: 'holographic-progress', isNew: true },
      { name: 'HolographicTerminal', slug: 'holographic-terminal', isNew: true },
    ],
  },
  {
    emoji: '🌐',
    title: '3D / 360° / AR-VR (tekivex-3d)',
    desc: 'Real WebGL primitives for spatial UI. Vanilla three.js, no reconciler.',
    components: [
      { name: 'Scene',          slug: 'scene' },
      { name: 'Card3D',         slug: 'card-3d' },
      { name: 'Panorama360',    slug: 'panorama-360' },
      { name: 'Hotspot',        slug: 'hotspot' },
      { name: 'XRSession',      slug: 'xr-session' },
      { name: 'Model3D',        slug: 'model-3d' },
      { name: 'Logo3D',         slug: 'logo-3d' },
      { name: 'ParticleField',  slug: 'particle-field' },
      { name: 'OrbitControls',  slug: 'orbit-controls' },
      { name: 'Starfield',      slug: 'starfield',     isNew: true },
      { name: 'Planet',         slug: 'planet',        isNew: true },
      { name: 'OrbitPath',      slug: 'orbit-path',    isNew: true },
      { name: 'Portal3D',       slug: 'portal-3d',     isNew: true },
      { name: 'Avatar3D',       slug: 'avatar-3d',     isNew: true },
    ],
  },
  {
    emoji: '🛠️',
    title: 'Productivity (v3.6 → v3.13)',
    desc: 'Spreadsheets, mind maps, gantts, kanbans, palettes — the heavy hitters.',
    components: [
      { name: 'Kanban',          slug: 'kanban',          isNew: true },
      { name: 'RichEditor',      slug: 'rich-editor',     isNew: true },
      { name: 'CalendarHeatmap', slug: 'calendar-heatmap',isNew: true },
      { name: 'FormBuilder',     slug: 'form-builder',    isNew: true },
      { name: 'MindMap',         slug: 'mind-map',        isNew: true },
      { name: 'Gantt',           slug: 'gantt',           isNew: true },
      { name: 'Spreadsheet',     slug: 'spreadsheet',     isNew: true },
      { name: 'PivotTable',      slug: 'pivot-table',     isNew: true },
      { name: 'DataExplorer',    slug: 'data-explorer',   isNew: true },
      { name: 'CommandPalette',  slug: 'command-palette', isNew: true },
      { name: 'FlowChart',       slug: 'flow-chart',      isNew: true },
      { name: 'ThemeStudio',     slug: 'theme-studio',    isNew: true },
      { name: 'AccessibilityChecker', slug: 'accessibility-checker', isNew: true },
    ],
  },
  {
    emoji: '📝',
    title: 'Form inputs',
    desc: 'Validated, accessible, sanitised',
    components: [
      { name: 'Autocomplete', slug: 'autocomplete' },
      { name: 'Checkbox', slug: 'checkbox' },
      { name: 'ColorPicker', slug: 'color-picker' },
      { name: 'CurrencyInput', slug: 'currency-input' },
      { name: 'DatePicker', slug: 'date-picker' },
      { name: 'FileUpload', slug: 'file-upload' },
      { name: 'Form', slug: 'form' },
      { name: 'Input', slug: 'input' },
      { name: 'NumberInput', slug: 'number-input' },
      { name: 'OTP', slug: 'otp' },
      { name: 'PhoneInput', slug: 'phone-input' },
      { name: 'Radio', slug: 'radio' },
      { name: 'Rating', slug: 'rating' },
      { name: 'Segmented', slug: 'segmented' },
      { name: 'Select', slug: 'select' },
      { name: 'Slider', slug: 'slider' },
      { name: 'Toggle', slug: 'toggle' },
    ],
  },
  {
    emoji: '🇮🇳',
    title: 'KYC + identity',
    desc: 'Indian + international ID inputs',
    components: [
      { name: 'AadhaarInput', slug: 'aadhaar-input' },
      { name: 'AddressInput', slug: 'address-input' },
      { name: 'KycInputs (PAN/VoterID/DL)', slug: 'kyc-inputs' },
    ],
  },
  {
    emoji: '🧭',
    title: 'Layout + navigation',
    desc: 'App shell + nav primitives',
    components: [
      { name: 'Affix', slug: 'affix' },
      { name: 'Anchor', slug: 'anchor' },
      { name: 'AppBar', slug: 'app-bar' },
      { name: 'BottomNav', slug: 'bottom-nav' },
      { name: 'ConfigProvider', slug: 'config-provider' },
      { name: 'Drawer', slug: 'drawer' },
      { name: 'Layout', slug: 'layout' },
      { name: 'Masonry', slug: 'masonry' },
      { name: 'Menu', slug: 'menu' },
      { name: 'SpeedDial', slug: 'speed-dial' },
      { name: 'Tabs', slug: 'tabs' },
      { name: 'Toolbar', slug: 'toolbar' },
      { name: 'Tour', slug: 'tour' },
    ],
  },
  {
    emoji: '📊',
    title: 'Display + content',
    desc: 'Read-mostly content',
    components: [
      { name: 'Accordion', slug: 'accordion' },
      { name: 'Carousel', slug: 'carousel' },
      { name: 'Clock', slug: 'clock' },
      { name: 'Markdown', slug: 'markdown' },
      { name: 'OrgChart', slug: 'org-chart' },
      { name: 'RichTextDisplay', slug: 'rich-text-display' },
      { name: 'Statistic', slug: 'statistic' },
      { name: 'Stepper', slug: 'stepper' },
      { name: 'Table', slug: 'table' },
      { name: 'Timeline', slug: 'timeline' },
      { name: 'Watermark', slug: 'watermark' },
    ],
  },
  {
    emoji: '💬',
    title: 'Overlays + feedback',
    desc: 'Modals, popovers, toasts',
    components: [
      { name: 'Modal', slug: 'modal' },
      { name: 'Popover', slug: 'popover' },
      { name: 'Snackbar', slug: 'snackbar' },
      { name: 'Toast', slug: 'toast' },
    ],
  },
  {
    emoji: '🗂️',
    title: 'Data widgets',
    desc: 'Selection, transfer, hierarchy',
    components: [
      { name: 'Cascader', slug: 'cascader' },
      { name: 'DataGrid', slug: 'data-grid' },
      { name: 'List', slug: 'list' },
      { name: 'Mentions', slug: 'mentions' },
      { name: 'Sortable', slug: 'sortable' },
      { name: 'TransferList', slug: 'transfer-list' },
      { name: 'TreeView', slug: 'tree-view' },
    ],
  },
  {
    emoji: '⚡',
    title: 'Real-time',
    desc: 'Timer-driven streaming widgets',
    components: [
      { name: 'LiveFeed', slug: 'live-feed' },
      { name: 'LiveLog', slug: 'live-log' },
      { name: 'LiveMetrics', slug: 'live-metrics' },
      { name: 'RealTimeChart', slug: 'real-time-chart' },
    ],
  },
  {
    emoji: '🤖',
    title: 'AI-native',
    desc: 'Built for LLM-powered UIs',
    components: [
      { name: 'AIChatBubble', slug: 'aichat-bubble' },
      { name: 'AIConfidenceBar', slug: 'aiconfidence-bar' },
      { name: 'AIThinking', slug: 'aithinking' },
      { name: 'Chat', slug: 'chat' },
    ],
  },
  {
    emoji: '📈',
    title: 'Charts',
    desc: 'recharts-powered, free',
    components: [
      { name: 'AreaChart', slug: 'area-chart' },
      { name: 'BarChart', slug: 'bar-chart' },
      { name: 'LineChart', slug: 'line-chart' },
      { name: 'PieChart', slug: 'pie-chart' },
    ],
  },
  {
    emoji: '🎬',
    title: 'Media + creative',
    desc: 'Cameras, signatures, QR',
    components: [
      { name: 'Confetti', slug: 'confetti' },
      { name: 'ImageEditor', slug: 'image-editor' },
      { name: 'QRCode', slug: 'qrcode' },
      { name: 'SignaturePad', slug: 'signature-pad' },
      { name: 'VideoPlayer', slug: 'video-player' },
    ],
  },
  {
    emoji: '💳',
    title: 'Commerce + fintech',
    desc: 'Payments, checkout, subs',
    components: [
      { name: 'Checkout', slug: 'checkout' },
      { name: 'PaymentButton', slug: 'payment-button' },
      { name: 'Subscription', slug: 'subscription' },
    ],
  },
  {
    emoji: '🛠️',
    title: 'Utility / infra',
    desc: 'Bot defense, fonts, SEO',
    components: [
      { name: 'Captcha', slug: 'captcha' },
      { name: 'Command (Cmd-K)', slug: 'command' },
      { name: 'FontProvider', slug: 'font-provider' },
      { name: 'Playground', slug: 'playground' },
      { name: 'SEO', slug: 'seo' },
      { name: 'ThemeBuilder', slug: 'theme-builder' },
    ],
  },
  {
    emoji: '🌐',
    title: '3D + 360° + AR/VR (tekivex-3d)',
    desc: 'WebGL primitives — separate package',
    components: [
      { name: 'Scene', slug: 'scene', isNew: true },
      { name: 'Card3D', slug: 'card-3d', isNew: true },
      { name: 'Panorama360', slug: 'panorama-360', isNew: true },
      { name: 'Hotspot', slug: 'hotspot', isNew: true },
      { name: 'XRSession', slug: 'xr-session', isNew: true },
    ],
  },
];

const TOTAL = GROUPS.reduce((n, g) => n + g.components.length, 0);

// Map group title hint → package name (used to pre-fill the request issue)
function pkgForGroup(title: string): string {
  if (/3D \/ 360°|tekivex-3d/i.test(title)) return 'tekivex-3d';
  return 'tekivex-ui';
}

export function AllComponents() {
  const [requested, setRequested] = useState<RequestTarget | null>(null);
  return (
    <section
      id="components"
      style={{ padding: '88px 24px 48px', maxWidth: 1280, margin: '0 auto' }}
    >
      <header style={{ textAlign: 'center', marginBottom: 40 }}>
        <h2
          style={{
            fontSize: 'clamp(1.8rem, 4vw, 2.8rem)',
            fontWeight: 800,
            letterSpacing: '-0.03em',
            margin: '0 0 12px',
          }}
        >
          Browse all <span className="tk-gradient-text">{TOTAL}</span> components
        </h2>
        <p style={{ color: '#1f2937', maxWidth: 660, margin: '0 auto', fontSize: 16, lineHeight: 1.65 }}>
          Click any component below to request access — we publish the latest
          source to npm on demand and email setup instructions back. Browse the
          full live catalog at{' '}
          <a href="/playground/" style={{ color: '#0f766e', fontWeight: 600 }}>
            /playground/
          </a>{' '}
          or storybook-style controls at{' '}
          <a href="/book/" style={{ color: '#0f766e', fontWeight: 600 }}>
            /book/
          </a>
          .
        </p>
      </header>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
          gap: 16,
        }}
      >
        {GROUPS.map((g) => (
          <div
            key={g.title}
            style={{
              padding: 22,
              borderRadius: 14,
              border: '1px solid #e5e7eb',
              background: '#ffffff',
              boxShadow:
                '0 1px 2px rgba(0,0,0,0.04), 0 1px 3px rgba(0,0,0,0.06)',
            }}
          >
            <header
              style={{
                display: 'flex',
                gap: 10,
                alignItems: 'center',
                marginBottom: 4,
              }}
            >
              <span style={{ fontSize: 22 }} aria-hidden="true">
                {g.emoji}
              </span>
              <h3
                style={{
                  margin: 0,
                  fontSize: 16,
                  fontWeight: 700,
                  color: '#0a0a0f',
                  letterSpacing: '-0.01em',
                }}
              >
                {g.title}
              </h3>
              <span
                style={{
                  marginLeft: 'auto',
                  color: '#6b7280',
                  fontSize: 12,
                  fontFamily: 'monospace',
                }}
              >
                {g.components.length}
              </span>
            </header>
            <p style={{ color: '#4b5563', fontSize: 12, margin: '0 0 14px' }}>{g.desc}</p>

            <ul
              style={{
                listStyle: 'none',
                padding: 0,
                margin: 0,
                display: 'flex',
                flexWrap: 'wrap',
                gap: 6,
              }}
            >
              {g.components.map((c) => {
                // Shared chip styling — used by both the <a> and the fallback <button>.
                const chipStyle: React.CSSProperties = {
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 4,
                  padding: '4px 10px',
                  borderRadius: 6,
                  background: '#fafbfc',
                  border: '1px solid #e5e7eb',
                  color: '#1f2937',
                  fontSize: 12,
                  fontWeight: 500,
                  transition: 'all 0.15s',
                  cursor: 'pointer',
                  fontFamily: 'inherit',
                  textDecoration: 'none',
                };
                const handleEnter = (e: React.MouseEvent<HTMLElement>) => {
                  e.currentTarget.style.color = '#0f766e';
                  e.currentTarget.style.borderColor = '#99f6e4';
                  e.currentTarget.style.background = '#f0fdfa';
                };
                const handleLeave = (e: React.MouseEvent<HTMLElement>) => {
                  e.currentTarget.style.color = '#1f2937';
                  e.currentTarget.style.borderColor = '#e5e7eb';
                  e.currentTarget.style.background = '#fafbfc';
                };
                const chipChildren = (
                  <>
                    {c.name}
                    {c.isNew && (
                      <span style={{ fontSize: 9, color: '#0f766e', fontWeight: 700, letterSpacing: '0.05em' }}>
                        NEW
                      </span>
                    )}
                  </>
                );

                return (
                  <li key={c.slug}>
                    {DOCUMENTED_SLUGS.has(c.slug) ? (
                      // Real docs page exists — link to it directly. No JS, no modal.
                      <a
                        href={`/components/${c.slug}/`}
                        style={chipStyle}
                        onMouseEnter={handleEnter}
                        onMouseLeave={handleLeave}
                      >
                        {chipChildren}
                      </a>
                    ) : (
                      // No docs page yet — open the request-access dialog so the
                      // maintainer sees demand for docs/source of this component.
                      <button
                        type="button"
                        onClick={() =>
                          setRequested({
                            name: c.name.startsWith('Tkx') ? c.name : `Tkx${c.name}`,
                            slug: c.slug,
                            pkg: pkgForGroup(g.title),
                          })
                        }
                        style={chipStyle}
                        onMouseEnter={handleEnter}
                        onMouseLeave={handleLeave}
                        title="Docs page not published yet — click to request"
                      >
                        {chipChildren}
                      </button>
                    )}
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </div>

      <div
        style={{
          textAlign: 'center',
          marginTop: 40,
          display: 'flex',
          justifyContent: 'center',
          gap: 12,
          flexWrap: 'wrap',
        }}
      >
        <a
          href="/playground/"
          style={{
            padding: '12px 24px',
            background: '#0d9488',
            color: '#ffffff',
            fontWeight: 700,
            borderRadius: 999,
            fontSize: 14,
            minHeight: 44,
            display: 'inline-flex',
            alignItems: 'center',
            gap: 8,
          }}
        >
          🎮 Open the playground →
        </a>
        <a
          href="/book/"
          style={{
            padding: '12px 24px',
            background: '#ffffff',
            border: '1px solid #e5e7eb',
            color: '#1f2937',
            fontWeight: 700,
            borderRadius: 999,
            fontSize: 14,
            minHeight: 44,
            display: 'inline-flex',
            alignItems: 'center',
            gap: 8,
          }}
        >
          📖 Open the catalog →
        </a>
      </div>

      <RequestAccessDialog target={requested} onClose={() => setRequested(null)} />
    </section>
  );
}
